services:

  postgres:
    image: pgvector/pgvector:pg18
    container_name: trackflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manhar
      POSTGRES_DB: Logestic_Go

    ports:
      - "5433:5432"

    volumes:
      - trackflow_postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Logestic_Go"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build: ./backend
    container_name: trackflow-backend
    restart: unless-stopped

    env_file:
      - ./backend/.env

    environment:
      DB_HOST: postgres
      DB_PORT: "5432"

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./backend:/app


  celery_worker:
    build: ./backend
    container_name: trackflow-celery-worker
    restart: unless-stopped

    env_file:
      - ./backend/.env

    environment:
      DB_HOST: postgres
      DB_PORT: "5432"

    command: celery -A config worker --loglevel=info

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./backend:/app


  celery_beat:
    build: ./backend
    container_name: trackflow-celery-beat
    restart: unless-stopped

    env_file:
      - ./backend/.env

    environment:
      DB_HOST: postgres
      DB_PORT: "5432"

    command: celery -A config beat --loglevel=info

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./backend:/app

  ai_service:
    build: ./ai_service
    container_name: trackflow-ai-service
    restart: unless-stopped

    env_file:
      - ./ai_service/.env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: Logestic_Go
      POSTGRES_USER: postgres
      PGVECTOR_COLLECTION: trackflow_documents
      PROJECT_DOCS_DIRS: /app/documents,/project-source/backend/docs
      PROJECT_SOURCE_DIRS: /app/documents,/project-source/backend/docs

    ports:
      - "8001:8000"

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./backend:/project-source/backend:ro
      - ./frontend:/project-source/frontend:ro
      - ./ai_service/documents:/app/documents:ro

  nginx:
    image: nginx:alpine
    container_name: trackflow-nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend
      - ai_service

volumes:
  trackflow_postgres_data: