# Generated by Django 6.0.6 on 2026-07-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
