# Generated by Django 6.0.6 on 2026-07-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_accountactivation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
